// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for goose_db_version */
export type GooseDbVersionId = number;

/** Represents the table public.goose_db_version */
export default interface GooseDbVersionTable {
  id: ColumnType<GooseDbVersionId, GooseDbVersionId | undefined, GooseDbVersionId>;

  versionId: ColumnType<string, string, string>;

  isApplied: ColumnType<boolean, boolean, boolean>;

  tstamp: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type GooseDbVersion = Selectable<GooseDbVersionTable>;

export type NewGooseDbVersion = Insertable<GooseDbVersionTable>;

export type GooseDbVersionUpdate = Updateable<GooseDbVersionTable>;
