// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type default as GooseDbVersionTable } from './GooseDbVersion';
import { type default as UserTable } from './User';
import { type default as TaskTable } from './Task';
import { type default as ContactTable } from './Contact';
import { type default as MessageTable } from './Message';

export default interface PublicSchema {
  gooseDbVersion: GooseDbVersionTable;

  user: UserTable;

  task: TaskTable;

  contact: ContactTable;

  message: MessageTable;
}
