// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.status */
enum Status {
  ongoing = 'ongoing',
  failed = 'failed',
  completed = 'completed',
  error = 'error',
};

export default Status;
