// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type UserId } from './User';
import { type default as Status } from './Status';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for task */
export type TaskId = number;

/** Represents the table public.task */
export default interface TaskTable {
  id: ColumnType<TaskId, TaskId | undefined, TaskId>;

  userId: ColumnType<UserId, UserId, UserId>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  title: ColumnType<string, string, string>;

  description: ColumnType<string | null, string | null, string | null>;

  finishTimestamp: ColumnType<Date, Date | string, Date | string>;

  status: ColumnType<Status, Status, Status>;

  completedTimestamp: ColumnType<Date | null, Date | string | null, Date | string | null>;

  failedRecipientEmail: ColumnType<string | null, string | null, string | null>;

  failedMessage: ColumnType<string | null, string | null, string | null>;

  errorMessage: ColumnType<string | null, string | null, string | null>;
}

export type Task = Selectable<TaskTable>;

export type NewTask = Insertable<TaskTable>;

export type TaskUpdate = Updateable<TaskTable>;
