name: CD

on:
  push:
    branches: [main]
    paths:
      - 'public/**'
      - 'src/**'
      - 'docs/apiDocs.json'
      - 'Dockerfile'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: doublethebass/countdown:latest

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Update and restart Droplet
        run: |
          doctl apps create-deployment d91efb75-2a9a-46cd-967e-bce9420ca0ad
